version: '3.7'

services:
  usermanagement_db:
    image: postgres:12.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=nest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres